- name: Setup Java
  uses: actions/setup-java@v4
  with:
    distribution: temurin
    java-version: 21

- name: Verify Java Version
  run: |
    java -version
    echo $JAVA_HOME

- name: Build APK
  run: |
    cd android
    chmod +x gradlew
    export JAVA_HOME=$JAVA_HOME
    ./gradlew assembleDebug --stacktrace